### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jak414** [Petto11/Symmetric_Key_Encryption#11]
Need to add the explanations regarding bigrams and how to proceed with that approach

**Comment by leo-corte** [comment]
The README file is now updated and comleted. Give it a read here: https://github.com/Petto11/Symmetric_Key_Encryption/commit/845a04eed26098a99a3807f5117605958337380 and let me know if it's okay, so then we can close the issue.

**Comment by Petto11** [comment]
For me the file it's okay, just a little bit of modifications on the structure of the text, but the content is great.

**Comment by Petto11** [comment]
Readme updated, waiting for some feedbacks

**Comment by jak414** [comment]
Ended by Petto11 at 3837077a1566fd3a5483c4c08c44ed049abc50d7
