### ISSUE TITLE
Cleaning/frequencies functions

### ISSUE THREAD

**Issue by jak414** [Petto11/Symmetric_Key_Encryption#4]
write the first functions useful to count the frequencies in a text file. we have to:
- clear the text (avoid punctuation, blank spaces)
- count the characters
- match the one in the cipher with the one in the corpus (tbd)

**Comment by ErChico6** [comment]
I added a first trial of the clean/frequency file and merged it right after.

Check the function here: https://github.com/Petto11/Symmetric_Key_Encryption/commit/449a20f064e1c8a1c8593f6918f150be5d3a0087

**Comment by Petto11** [comment]
There's a problem with the cleaning function: when it encounters \n, it removes just the "\" character but leaves the n. We want to avoid this in order not to bias character frequency.

**Comment by Petto11** [comment]
The part was added here: https://github.com/Petto11/Symmetric_Key_Encryption/commit/9e5f35f7010870baf553ffa978f3ecfb8bb4b56a. 
Tomorrow morning I will start working on the cleaning function and by 13.00 I'll update it.

**Comment by Petto11** [comment]
Added the frequency function here: https://github.com/Petto11/Symmetric_Key_Encryption/commit/2c7faabf9ee76b404f73e42a0b50b91e48b4f5c8. 
Everything works, can close the issue.
