### ISSUE TITLE
Building a Key

### ISSUE THREAD

**Issue by Petto11** [Petto11/Symmetric_Key_Encryption#6]
The next step is writing a function that, given as input the frequency of the corpus and the frequency of the cipher, builds a symmetric key.

**Comment by dianalorenzo** [comment]
How? Because I technically understand how to create the two frequencies of characters, but how should these two relate with each other in order to create a key?

**Comment by Petto11** [comment]
You should match them using a dictionary having has key the frequency of the cipher while as values the frequency of the corpus. Then you should alphabetically order the keys of the dictionary, maintaining unaltered the association with the values.

**Comment by dianalorenzo** [comment]
Got It, now I'll try to do it

**Comment by leo-corte** [comment]
Be careful that in this part (https://github.com/Petto11/Symmetric_Key_Encryption/commit/15de5f08388c71e9ec02ba5fef856a11ec43150c) you did not create a branch. Also, you can make the code fancier using ascii.lowercase instead of the string containing the 26 letters.

**Comment by leo-corte** [comment]
Made the code fancier here : https://github.com/Petto11/Symmetric_Key_Encryption/commit/7860cd6a08328338de6cc1aae4926288743c1a89. Everything works so we can close the issue.
