### ISSUE TITLE
created the bigram function

### ISSUE THREAD

**Issue by dianalorenzo** [Petto11/Symmetric_Key_Encryption#9]

**Comment by Petto11** [comment]
In the evening I will push the function that finds the frequency of the bigrams in a text

**Comment by Petto11** [comment]
Competed here : https://github.com/Petto11/Symmetric_Key_Encryption/commit/a7e548ba9e78d55e317792fbae6c430bd35bf911

**Comment by Petto11** [comment]
I added the scoring function to the Bigram.py file. Now we need the function that create all the possible permutations of the key. Anyone willing to do it?

**Comment by ErChico6** [comment]
I can do it. Someone can help me and create a function which simply swap two characters while I work on the function permute, since I will surely need something like that?
Thanks

**Comment by ErChico6** [comment]
I confirm that I added the permute function on Bigram.py file.
Completed what said here: https://github.com/Petto11/Symmetric_Key_Encryption/issues/9#issuecomment-986035671

**Comment by leo-corte** [comment]
I'm on the swap function, give me a bunch of minutes and i'll upload it.

**Comment by leo-corte** [comment]
Added the function here: https://github.com/Petto11/Symmetric_Key_Encryption/commit/563b530072ae505ae28dc097b6b88c18511ddd87.
Noow you can move on with the permute function.

**Comment by dianalorenzo** [comment]
Guys, I have uploaded the final function that we have discussed today after class. I called it bruteforce, and It should work. The fact is that I didn't manage to  incorporate the argparse module. I'll close this issue and open another one at this point
